<a href="https://colab.research.google.com/github/anil2k/Image-classification-from-scratch-keras-/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(256, 256,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
 # this converts our 3D feature maps to 1D feature vectors
model.add(Flatten()) 
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(4))
model.add(Activation('softmax'))

model.compile(loss='CategoricalCrossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.summary()

#for two class activation: sigmoid Dence:1 loss: BinaryCrossentropy
#for more than two: softmax Dence : no of classes loss: CategoricalCrossentropy

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 254, 254, 32)      896       
_________________________________________________________________
activation_25 (Activation)   (None, 254, 254, 32)      0         
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 127, 127, 32)      0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 125, 125, 32)      9248      
_________________________________________________________________
activation_26 (Activation)   (None, 125, 125, 32)      0         
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 62, 62, 32)        0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 60, 60, 64)       

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
batch_size = 16
img_height=256
img_width=256

train_datagen = ImageDataGenerator(rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2) # set validation split
train_data_dir='/content/drive/MyDrive/assignment/Busigence_Technologies/Input/Dataset/train'
train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training') # set as training data

validation_generator = train_datagen.flow_from_directory(
    train_data_dir, # same directory as training data
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation') # set as validation data

print(train_generator.class_indices)
print(train_generator.class_indices)

Found 354 images belonging to 4 classes.
Found 86 images belonging to 4 classes.
{'category_1': 0, 'category_2': 1, 'category_3': 2, 'category_4': 3}
{'category_1': 0, 'category_2': 1, 'category_3': 2, 'category_4': 3}


In [ ]:
nb_epochs=20
model.fit_generator(
    train_generator,
    steps_per_epoch = train_generator.samples // batch_size,
    validation_data = validation_generator, 
    validation_steps = validation_generator.samples // batch_size,
    epochs = nb_epochs)
model.save('/content/drive/MyDrive/assignment/Busigence_Technologies/Output/first_try.h5')  # always save your weights after training or during training

/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:1915: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/20
22/22 [==============================] - 9s 420ms/step - loss: 0.0789 - accuracy: 0.9659 - val_loss: 0.6874 - val_accuracy: 0.8250
Epoch 2/20
22/22 [==============================] - 9s 405ms/step - loss: 0.0656 - accuracy: 0.9734 - val_loss: 0.5081 - val_accuracy: 0.8625
Epoch 3/20
22/22 [==============================] - 9s 404ms/step - loss: 0.0739 - accuracy: 0.9793 - val_loss: 0.5536 - val_accuracy: 0.8500
Epoch 4/20
22/22 [==============================] - 9s 411ms/step - loss: 0.0539 - accuracy: 0.9793 - val_loss: 0.6548 - val_accuracy: 0.8500
Epoch 5/20
22/22 [==============================] - 9s 403ms/step - loss: 0.1007 - accuracy: 0.9763 - val_loss: 0.4355 - val_accuracy: 0.8375
Epoch 6/20
22/22 [==============================] - 9s 400ms/step - loss: 0.0265 - accuracy: 0.9882 - val_loss: 0.6536 - val_accuracy: 0.8250
Epoch 7/20
22/22 [==============================] - 9s 404ms/step - loss: 0.0584 - accuracy: 0.9822 - val_loss: 0.6142 - val_accuracy: 0.8250
Epoch 

In [ ]:
from keras.models import load_model
model1 = load_model('/content/drive/MyDrive/assignment/Busigence_Technologies/Output/first_try.h5')
model1.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 254, 254, 32)      896       
_________________________________________________________________
activation_25 (Activation)   (None, 254, 254, 32)      0         
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 127, 127, 32)      0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 125, 125, 32)      9248      
_________________________________________________________________
activation_26 (Activation)   (None, 125, 125, 32)      0         
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 62, 62, 32)        0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 60, 60, 64)       

In [ ]:
import os
import glob
import cv2
test_img = []
for img in glob.glob("/content/drive/MyDrive/assignment/Busigence_Technologies/Input/Dataset/test/*.png"):
    #n= cv2.imread(img)
    test_img.append(img)
print(len(test_img))
print(test_img[1])


30
/content/drive/MyDrive/assignment/Busigence_Technologies/Input/Dataset/test/4051.png


In [ ]:
import keras
import tensorflow as tf
image_size = (256, 256)
result=[]
for a in test_img:
  img = keras.preprocessing.image.load_img(
    a, target_size=image_size
    )
  img_array = keras.preprocessing.image.img_to_array(img)
  #img_array.shape
  img_array = tf.expand_dims(img_array, 0)  # Create batch axis
  #print(img_array.shape)
  predictions = model1.predict(img_array)
  print(predictions)

  if int((predictions[0][0]))==1:
    pred='category_1'
  if int(predictions[0][1])==1:
    pred='category_2'
  if int(predictions[0][2])==1:
    pred='category_3'
  if int(predictions[0][3])==1:
    pred='category_4'
  pred_row=[a[76:],pred]
  result.append(pred_row)
#{'category_1': 0, 'category_2': 1, 'category_3': 2, 'category_4': 3}

score = predictions[0]
print(predictions[0][1])


[[0. 0. 1. 0.]]
[[0. 0. 1. 0.]]
[[0. 1. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 0. 1.]]
[[0. 1. 0. 0.]]
[[1. 0. 0. 0.]]
[[0. 0. 0. 1.]]
[[1. 0. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 1. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 1. 0. 0.]]
[[0. 0. 0. 1.]]
[[0. 1. 0. 0.]]
[[1. 0. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 0. 1.]]
[[0. 1. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 1. 0.]]
[[0. 1. 0. 0.]]
[[0. 0. 1. 0.]]
[[0. 0. 0. 1.]]
[[0. 1. 0. 0.]]
1.0


In [ ]:
result

[['4052.png', 'category_3'],
 ['4051.png', 'category_3'],
 ['6052.png', 'category_2'],
 ['4050.png', 'category_3'],
 ['C053.png', 'category_4'],
 ['6053.png', 'category_2'],
 ['1052.png', 'category_1'],
 ['C052.png', 'category_4'],
 ['1051.png', 'category_1'],
 ['4043.png', 'category_3'],
 ['Test_original_4052.png_31cd9a66-9edc-4445-b4bc-9b0239b342e0.png',
  'category_3'],
 ['Test_original_4052.png_78b7cca7-2a16-4f3c-829d-e4937b5f2dc2.png',
  'category_3'],
 ['Test_original_1052.png_b95bc311-bae0-48a7-8b9f-d0eddf1ddf2b.png',
  'category_1'],
 ['Test_original_1052.png_22a82512-5b1f-4072-a4af-9a8af40653f0.png',
  'category_1'],
 ['Test_original_6052.png_9950e35a-38c7-4388-b391-ce50bb8ea1a7.png',
  'category_2'],
 ['Test_original_4043.png_fffcbc29-3aff-40c0-bdf9-2c12fa6df60b.png',
  'category_3'],
 ['Test_original_6052.png_51c87ecf-ede6-4152-960f-4d56ff913d53.png',
  'category_2'],
 ['Test_original_C052.png_5c226e55-09ba-4fd0-bf6b-e0d2b411baa3.png',
  'category_4'],
 ['Test_original_6053.

In [ ]:
import csv 
    
# field names 
fields = ['imageid','predicted_label'] 
    

# name of csv file 
filename = "/content/drive/MyDrive/assignment/Busigence_Technologies/Output/results1.csv"
    
# writing to csv file 
with open(filename, 'w') as csvfile: 
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
        
    # writing the fields 
    csvwriter.writerow(fields) 
        
    # writing the data rows 
    csvwriter.writerows(result)